apiVersion: v1 
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: # Labels are used as selectors here, this service will be attached to the pod whose labels matches the selectors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80 # Service port
    targetPort: 80 
    nodePort: {{ .Values.service.nodePort }} # Imagine this will change just for practise purposes

